
export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS"
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL"
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST"

export const SELECTED_VIDEO_REQUEST = "SELECTED_VIDEO_REQUEST"
export const SELECTED_VIDEO_SUCCESS = "SELECTED_VIDEO_SUCCESS"
export const SELECTED_VIDEO_FAIL = "SELECTED_VIDEO_FAIL"

export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST"
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS"
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL"

export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS"


export const SEARCHED_VIDEO_REQUEST = "SEARCHED_VIDEO_REQUEST"
export const SEARCHED_VIDEO_SUCCESS = "SEARCHED_VIDEO_SUCCESS"
export const SEARCHED_VIDEO_FAIL = "SEARCHED_VIDEO_FAIL"